baseURL: "https://yichi170.github.io/"
title: "Yi-Chi Lee"
theme: "PaperMod"

buildDrafts: false
enableEmoji: true
languageCode: "en-us"
disqusShortname: "yichi-1"

menu:
  main:
    - name: About
      url: "/"
      weight: 1
    - name: Experience
      url: "/experience"
      weight: 2
    - name: Publications
      url: "/publications"
      weight: 3
    - name: Activities
      url: "/activities"
      weight: 4
    # - name: Blog
    #   url: "/posts"

params:
  env: production
  author: "Yi-Chi Lee"

  profileMode:
    enabled: true
    title: "Yi-Chi Lee"
    imageUrl: head.JPEG
    imageTitle: "Profile image"
    buttons:
      - name: Posts
        url: "/posts"
      - name: Github
        url: "https://github.com/yichi170"

  homeInfoParams:
    Title: "Yi-Chi Lee"
    Content: >
      Hi, I'm Yi-Chi. Welcome to my blog.

  socialIcons:
    - name: Email
      url: "mailto:yichi170@gmail.com"
    - name: Github
      url: "https://github.com/yichi170"
    - name: Linkedin
      url: "https://www.linkedin.com/in/yichi170/"
    - name: GoogleScholar
      url: "https://scholar.google.com/citations?user=yCwUAwQAAAAJ"

  comments: true

minify:
  disableXML: true

outputs:
  home:
    - HTML
    - JSON
markup:
  goldmark:
    renderer:
      unsafe: true
